### ISSUE TITLE
pyinstaller

### ISSUE THREAD

**Issue by magne92** [FredrikFreding/Password-generator#1]
Alle kommandoer kjøres i CMD – kommandoer er merket med svart

installer pyinstaller:

py -m pip install PyInstaller

lage exe fil:
naviger til mappen der du har lagret python filen din.
EKSEMPEL: 
cd c:\users\%username%\dokumenter\python\

deretter kjør kommando:

py -m PyInstaller --onefile eksempelnavn.py

store og små bokstaver må være likt i kommandoen over

**Comment by FredrikFreding** [comment]
Gjorde dette, .exe filen ligger i "dist" mappen.

Husker ikke om jeg brukte "-m".
